### ISSUE TITLE
Request to release a build for scala 2.11

### ISSUE THREAD

**Issue by kcsham** [backchatio/hookup#19]
I'm using hookup as websocket client in my project to perform integration test against a running API service. I'm trying to move up to Scala 2.11 and hookup does not have an official 2.11 build yet. I've tried to modify the master snapshot to get it to build with 2.11. I had to manually up akka, specs2 to newer versions, and override a transient org.scalaz.stream dependency. After which, source compiles; there are more to fix in the test though.

I'm wondering if the team has capacity to release 0.4.1 with 2.11 support.

**Comment by casualjim** [comment]
Unfortunately I've left scala for what it is and moved on to a more effective language for me. 
I've kept this project here more as a guide for people or to serve as an example.

That being said if somebody does the work i'll merge and publish the jar that's no problem for me.

**Comment by casualjim** [comment]
also there is this: https://github.com/backchatio/hookup/issues/14

so i think 0.3.0 should be published for 2.11 if that's not the case I can re-publish it.

**Comment by kcsham** [comment]
My bad. I didn't check the 'closed' issues #14. I pulled 0.3.0-SNAPSHOT and built that. That works for what I need.

**Comment by michaelahlers** [comment]
I don't see any Hookup releases (or snapshots) for Scala 2.11. @casualjim, were there any issues publishing the artifacts?

**Comment by casualjim** [comment]
I've published a 0.3.0 (non-snapshot) built against 2.11.5
